### PR TITLE
v1.3 build 9

### PR DESCRIPTION
**Pull request by DanWebster**

### CODE REVIEW

**Comment by dephillipsmichael** [comment]
The changes to the libraries are probably fine but it's best to keep the same version of the libraries we are using when making a build

**Comment by DanWebster** [comment]
@dephillipsmichael I didn't carthage update before building this.  Do you see differences in the framework pointers that might have an adverse effect on the submitted build?

**Comment by dephillipsmichael** [comment]
@DanWebster I figured it was unintentional. I wonder why it updated behind the scenes?  

I'll have to look at the code that changed, it's late here so I'll check it out tomorrow morning.

**Comment by dephillipsmichael** [comment]
After reviewing the code, we should be fine.  We don't use the report manager, profile items, or tracked items which is where most of the code changes were.  There was one change to the schedule manager but it was to a function we were overriding anyways so it will have no effect.

**Pull request merged**
